import type { IconSet } from './index';

const base = '/icons/gaming-platforms';

export const gamingPlatforms: IconSet = {
  slug: 'gaming-platforms',
  name: 'Gaming Platforms',
  icons: {
    '3DS': { src: `${base}/3ds.svg`, alt: '3DS' },
    Amiga: { src: `${base}/amiga.svg`, alt: 'Amiga' },
    Atari: { src: `${base}/atari.svg`, alt: 'Atari' },
    'Commodore 64': { src: `${base}/commodore64.svg`, alt: 'Commodore 64' },
    'DS Lite': { src: `${base}/ds-lite.svg`, alt: 'DS Lite' },
    Dreamcast: { src: `${base}/dreamcast.svg`, alt: 'Dreamcast' },
    'Game Boy': { src: `${base}/gameboy.svg`, alt: 'Game Boy' },
    'Game Boy Advance': { src: `${base}/gameboy-advance.svg`, alt: 'Game Boy Advance' },
    'Game Boy Color': { src: `${base}/gameboy-color.svg`, alt: 'Game Boy Color' },
    GameCube: { src: `${base}/gamecube.svg`, alt: 'GameCube' },
    'Mega Drive': { src: `${base}/megadrive.svg`, alt: 'Mega Drive' },
    N64: { src: `${base}/n64.svg`, alt: 'N64' },
    NES: { src: `${base}/nes.svg`, alt: 'NES' },
    Oculus: { src: `${base}/oculus.svg`, alt: 'Oculus' },
    PC: { src: `${base}/pc.svg`, alt: 'PC' },
    PS1: { src: `${base}/ps1.svg`, alt: 'PS1' },
    PS2: { src: `${base}/ps2.svg`, alt: 'PS2' },
    PS3: { src: `${base}/ps3.svg`, alt: 'PS3' },
    PS4: { src: `${base}/ps4.svg`, alt: 'PS4' },
    PS5: { src: `${base}/ps5.svg`, alt: 'PS5' },
    Saturn: { src: `${base}/saturn.svg`, alt: 'Saturn' },
    SNES: { src: `${base}/snes.svg`, alt: 'SNES' },
    'Steam Deck': { src: `${base}/steamdeck.svg`, alt: 'Steam Deck' },
    Switch: { src: `${base}/switch.svg`, alt: 'Switch' },
    'Switch 2': { src: `${base}/switch-2.svg`, alt: 'Switch 2' },
    Wii: { src: `${base}/wii.svg`, alt: 'Wii' },
    'Wii U': { src: `${base}/wii-u.svg`, alt: 'Wii U' },
    Xbox: { src: `${base}/xbox.svg`, alt: 'Xbox' },
    'Xbox 360': { src: `${base}/xbox-360.svg`, alt: 'Xbox 360' },
    'Xbox One': { src: `${base}/xbox-one.svg`, alt: 'Xbox One' },
    'Xbox Series S/X': { src: `${base}/xbox-series-sx.svg`, alt: 'Xbox Series S/X' },
  },
};
