blank_issues_enabled: false
contact_links:
  - name: Security report
    url: https://github.com/tierdom/tierdom-app/blob/main/SECURITY.md
    about: See SECURITY.md for instructions about reporting security issues.
